# Generated by Django 5.2.17 on 2026-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_farmer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
